version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: auth
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: manh@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  eureka-server:
    image: manhnguyen9810124/sales-management:eureka-server-0.0.1
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - backend

  config-server:
    image: manhnguyen9810124/sales-management:config-server-0.0.1
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - GIT_USER_NAME
      - GIT_PASS_WORD
      - CONFIG_SERVER_URI=http://config-server:8888
    networks:
      - backend
    depends_on:
      - eureka-server

  auth-service:
    image: manhnguyen9810124/sales-management:auth-service-0.0.1
    container_name: auth-service
    ports:
      - "9000:9000"
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - backend
    depends_on:
      - eureka-server
      - config-server

  product-service:
    image: manhnguyen9810124/sales-management:product-service-0.0.1
    container_name: product-service
    ports:
      - "9001:9001"
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - backend
    depends_on:
      - eureka-server
      - config-server

  order-service:
    image: manhnguyen9810124/sales-management:order-service-0.0.1
    container_name: order-service
    ports:
      - "9002:9002"
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - backend
    depends_on:
      - eureka-server
      - config-server

  reports-service:
    image: manhnguyen9810124/sales-management:reports-service-0.0.1
    container_name: reports-service
    ports:
      - "9003:9003"
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - backend
    depends_on:
      - eureka-server
      - config-server

  api-gateway:
    image: manhnguyen9810124/sales-management:api-gateway-0.0.1
    container_name: api-gateway
    ports:
      - "9004:9004"
    environment:
      - CONFIG_SERVER_URI=http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - backend
    depends_on:
      - order-service
      - product-service
      - auth-service
      - reports-service

  notification-service:
    image: manhnguyen9810124/sales-management:notification-service-0.0.1
    container_name: notification-service
    networks:
      - backend
    depends_on:
      - eureka-server
      - config-server
      - kafka

volumes:
  pgdata:

networks:
  backend:
    driver: bridge