spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

server:
  port: 9004
logging:
  level:
    org.springframework.cloud.gateway: DEBUG