spring:
  application:
    name: reports-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 9003
logging:
  level:
    org.springframework.security: DEBUG