server:
  port: 9002
spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 1
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
