spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Manhnguyen981024/freeLancer.git
          username: ${GIT_USER_NAME}
          password: ${GIT_PASS_WORD}

server:
  port: 8888