# .github/workflows/build-all.yml
name: CI/CD All Services

on:
  push:
    branches: [ main ]

jobs:
  build-auth:
    runs-on: ubuntu-latest
    name: Build auth-service
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          push: true
          tags: manhnguyen9810124/sales-management:auth-service

  build-product:
    runs-on: ubuntu-latest
    name: Build product-service
    steps:
      - uses: actions/checkout@v3
      - name: Build product-service
        run: |
          cd product-service
          chmod +x mvnw      # ✅ thêm dòng này
          ./mvnw clean install -DskipTests

  build-eureka:
    runs-on: ubuntu-latest
    name: Build eureka-server
    steps:
      - uses: actions/checkout@v3
      - name: Build eureka-server
        run: |
          cd eureka-server
          chmod +x mvnw      # ✅ thêm dòng này
          ./mvnw clean install -DskipTests
